[package]
name = "Counter"
version = "0.0.1"
edition = "2024"

[dependencies]
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "main" }

[addresses]
counter = "0x0"
