/**
 * counter package ABI definition with TypeScript interfaces
 * 自動生成されたファイル - 手動で編集しないでください
 *
 * Generated by: scripts/suigenv0.ts
 * Generated at: 2025-09-26T19:01:59.007Z
 */

import {
  type Transaction,
  type TransactionArgument,
  type TransactionResult,
} from "@mysten/sui/transactions";

export const counterAbi = {
  multi_ibs_counter: {
    fileFormatVersion: 6,
    address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
    name: "multi_ibs_counter",
    friends: [],
    structs: {
      AggregatedPublicKey: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "public_key_g2",
            type: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            name: "counter_id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            name: "key_server_count",
            type: "U64",
          },
          {
            name: "included_key_server_ids",
            type: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
        ],
      },
      MultiIBSConfig: {
        abilities: {
          abilities: ["Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "key_server_ids",
            type: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
          {
            name: "threshold",
            type: "U64",
          },
        ],
      },
      MultiIBSCounter: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
          {
            name: "config",
            type: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSConfig",
                typeArguments: [],
              },
            },
          },
        ],
      },
      MultiIBSProof: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "counter_id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            name: "verified_signer_count",
            type: "U64",
          },
        ],
      },
    },
    exposedFunctions: {
      add_key_server_public_key: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      aggregated_key_counter_id: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x2",
              module: "object",
              name: "ID",
              typeArguments: [],
            },
          },
        ],
      },
      destroy_aggregated_public_key: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Struct: {
              address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
              module: "multi_ibs_counter",
              name: "AggregatedPublicKey",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      included_key_server_count: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      included_key_server_ids: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
        ],
      },
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
          {
            Struct: {
              address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
              module: "multi_ibs_counter",
              name: "MultiIBSProof",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      key_server_count: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      key_server_ids: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
        ],
      },
      new_aggregated_public_key: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
              module: "multi_ibs_counter",
              name: "AggregatedPublicKey",
              typeArguments: [],
            },
          },
        ],
      },
      public_key_g2: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
      share: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Vector: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          "U64",
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      threshold: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      verify_and_create_proof: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "MultiIBSCounter",
                typeArguments: [],
              },
            },
          },
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "multi_ibs_counter",
                name: "AggregatedPublicKey",
                typeArguments: [],
              },
            },
          },
          {
            Vector: "U8",
          },
          {
            Vector: "U8",
          },
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
              module: "multi_ibs_counter",
              name: "MultiIBSProof",
              typeArguments: [],
            },
          },
        ],
      },
    },
  },
  owned_counter: {
    fileFormatVersion: 6,
    address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
    name: "owned_counter",
    friends: [],
    structs: {
      OwnedCounter: {
        abilities: {
          abilities: ["Store", "Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
        ],
      },
    },
    exposedFunctions: {
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      new: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
              module: "owned_counter",
              name: "OwnedCounter",
              typeArguments: [],
            },
          },
        ],
      },
      set_value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
          "U64",
        ],
        return: [],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
    },
  },
  shared_counter: {
    fileFormatVersion: 6,
    address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
    name: "shared_counter",
    friends: [],
    structs: {
      SharedCounter: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
        ],
      },
    },
    exposedFunctions: {
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      set_value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
          "U64",
        ],
        return: [],
      },
      share: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0xaebd2bd0e1dc32b33e9e48363683af1e267c1943108c61250609064dede5d51b",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
    },
  },
} as const;

export type CounterModules = typeof counterAbi;

// Generated TypeScript interfaces
export interface Multi_ibs_counterAggregatedPublicKeyType {
  id: { id: string };
  public_key_g2: unknown;
  counter_id: unknown;
  key_server_count: string;
  included_key_server_ids: unknown[];
}

export interface Multi_ibs_counterMultiIBSConfigType {
  key_server_ids: unknown[];
  threshold: string;
}

export interface Multi_ibs_counterMultiIBSCounterType {
  id: { id: string };
  value: string;
  config: unknown;
}

export interface Multi_ibs_counterMultiIBSProofType {
  id: { id: string };
  counter_id: unknown;
  verified_signer_count: string;
}

export interface Owned_counterOwnedCounterType {
  id: { id: string };
  value: string;
}

export interface Shared_counterSharedCounterType {
  id: { id: string };
  value: string;
}

// Generated type guards
export function isMulti_ibs_counterAggregatedPublicKeyType(
  data: unknown,
): data is Multi_ibs_counterAggregatedPublicKeyType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = [
    "id",
    "public_key_g2",
    "counter_id",
    "key_server_count",
    "included_key_server_ids",
  ];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["key_server_count"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isMulti_ibs_counterMultiIBSConfigType(
  data: unknown,
): data is Multi_ibs_counterMultiIBSConfigType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["key_server_ids", "threshold"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["threshold"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isMulti_ibs_counterMultiIBSCounterType(
  data: unknown,
): data is Multi_ibs_counterMultiIBSCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value", "config"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isMulti_ibs_counterMultiIBSProofType(
  data: unknown,
): data is Multi_ibs_counterMultiIBSProofType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "counter_id", "verified_signer_count"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["verified_signer_count"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isOwned_counterOwnedCounterType(
  data: unknown,
): data is Owned_counterOwnedCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isShared_counterSharedCounterType(
  data: unknown,
): data is Shared_counterSharedCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

// Generated parse functions
export function parseMulti_ibs_counterAggregatedPublicKey(
  json: unknown,
): Multi_ibs_counterAggregatedPublicKeyType | null {
  return isMulti_ibs_counterAggregatedPublicKeyType(json) ? json : null;
}

export function parseMulti_ibs_counterMultiIBSConfig(
  json: unknown,
): Multi_ibs_counterMultiIBSConfigType | null {
  return isMulti_ibs_counterMultiIBSConfigType(json) ? json : null;
}

export function parseMulti_ibs_counterMultiIBSCounter(
  json: unknown,
): Multi_ibs_counterMultiIBSCounterType | null {
  return isMulti_ibs_counterMultiIBSCounterType(json) ? json : null;
}

export function parseMulti_ibs_counterMultiIBSProof(
  json: unknown,
): Multi_ibs_counterMultiIBSProofType | null {
  return isMulti_ibs_counterMultiIBSProofType(json) ? json : null;
}

export function parseOwned_counterOwnedCounter(
  json: unknown,
): Owned_counterOwnedCounterType | null {
  return isOwned_counterOwnedCounterType(json) ? json : null;
}

export function parseShared_counterSharedCounter(
  json: unknown,
): Shared_counterSharedCounterType | null {
  return isShared_counterSharedCounterType(json) ? json : null;
}

// Extract packageId once at module level for better performance
const packageId = Object.values(counterAbi)[0]?.address;
if (!packageId) {
  throw new Error("Package ID not found in counter ABI");
}

// Type-safe method-chaining API
export const counterPackage = {
  abi: counterAbi,
  packageId,
  multi_ibs_counter: {
    add_key_server_public_key(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::add_key_server_public_key`,
        arguments: [...options.arguments],
      });
    },
    aggregated_key_counter_id(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::aggregated_key_counter_id`,
        arguments: [...options.arguments],
      });
    },
    destroy_aggregated_public_key(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::destroy_aggregated_public_key`,
        arguments: [...options.arguments],
      });
    },
    included_key_server_count(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::included_key_server_count`,
        arguments: [...options.arguments],
      });
    },
    included_key_server_ids(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::included_key_server_ids`,
        arguments: [...options.arguments],
      });
    },
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    key_server_count(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::key_server_count`,
        arguments: [...options.arguments],
      });
    },
    key_server_ids(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::key_server_ids`,
        arguments: [...options.arguments],
      });
    },
    new_aggregated_public_key(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::new_aggregated_public_key`,
        arguments: [...options.arguments],
      });
    },
    public_key_g2(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::public_key_g2`,
        arguments: [...options.arguments],
      });
    },
    share(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::share`,
        arguments: [...options.arguments],
      });
    },
    threshold(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::threshold`,
        arguments: [...options.arguments],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::value`,
        arguments: [...options.arguments],
      });
    },
    verify_and_create_proof(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::multi_ibs_counter::verify_and_create_proof`,
        arguments: [...options.arguments],
      });
    },
  },
  owned_counter: {
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    new(tx: Transaction): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::new`,
        arguments: [],
      });
    },
    set_value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::set_value`,
        arguments: [...options.arguments],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::value`,
        arguments: [...options.arguments],
      });
    },
  },
  shared_counter: {
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    set_value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::set_value`,
        arguments: [...options.arguments],
      });
    },
    share(tx: Transaction): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::share`,
        arguments: [],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::value`,
        arguments: [...options.arguments],
      });
    },
  },
} as const;
