/**
 * counter package ABI definition with TypeScript interfaces
 * 自動生成されたファイル - 手動で編集しないでください
 *
 * Generated by: scripts/suigenv0.ts
 * Generated at: 2025-09-27T08:26:57.472Z
 */

import {
  type Transaction,
  type TransactionArgument,
  type TransactionResult,
} from "@mysten/sui/transactions";

export const counterAbi = {
  bls_multisig_counter: {
    fileFormatVersion: 6,
    address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
    name: "bls_multisig_counter",
    friends: [],
    structs: {
      BlsAggregatedPk: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "public_key_g2",
            type: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            name: "public_key_bytes",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "counter_id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            name: "seal_shard_count",
            type: "U64",
          },
          {
            name: "included_seal_shard_ids",
            type: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
        ],
      },
      BlsMultisigConfig: {
        abilities: {
          abilities: ["Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "seal_shard_table",
            type: {
              Struct: {
                address: "0x2",
                module: "table",
                name: "Table",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "object",
                      name: "ID",
                      typeArguments: [],
                    },
                  },
                  {
                    Struct: {
                      address: "0x2",
                      module: "group_ops",
                      name: "Element",
                      typeArguments: [
                        {
                          Struct: {
                            address: "0x2",
                            module: "bls12381",
                            name: "G2",
                            typeArguments: [],
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            },
          },
          {
            name: "threshold",
            type: "U64",
          },
        ],
      },
      BlsMultisigCounter: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
          {
            name: "config",
            type: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigConfig",
                typeArguments: [],
              },
            },
          },
        ],
      },
      BlsMultisigProof: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "counter_id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            name: "verified_signer_count",
            type: "U64",
          },
        ],
      },
      PackageMarker: {
        abilities: {
          abilities: ["Drop"],
        },
        typeParameters: [],
        fields: [
          {
            name: "dummy_field",
            type: "Bool",
          },
        ],
      },
    },
    exposedFunctions: {
      aggregate_seal_shard_pubkey: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
          {
            Struct: {
              address: "0x2",
              module: "object",
              name: "ID",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      aggregated_key_counter_id: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x2",
              module: "object",
              name: "ID",
              typeArguments: [],
            },
          },
        ],
      },
      destroy_bls_aggregated_pk: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Struct: {
              address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
              module: "bls_multisig_counter",
              name: "BlsAggregatedPk",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      get_package_id_bytes: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [],
        return: [
          {
            Vector: "U8",
          },
        ],
      },
      included_seal_shard_count: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      included_seal_shard_ids: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "object",
                  name: "ID",
                  typeArguments: [],
                },
              },
            },
          },
        ],
      },
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
          {
            Struct: {
              address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
              module: "bls_multisig_counter",
              name: "BlsMultisigProof",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      new_bls_aggregated_pk: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
              module: "bls_multisig_counter",
              name: "BlsAggregatedPk",
              typeArguments: [],
            },
          },
        ],
      },
      public_key_g2: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
      seal_approve: {
        visibility: "Private",
        isEntry: true,
        typeParameters: [],
        parameters: [
          {
            Vector: "U8",
          },
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
          {
            Vector: "U8",
          },
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      seal_shard_count: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      seal_shard_table: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "table",
                name: "Table",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "object",
                      name: "ID",
                      typeArguments: [],
                    },
                  },
                  {
                    Struct: {
                      address: "0x2",
                      module: "group_ops",
                      name: "Element",
                      typeArguments: [
                        {
                          Struct: {
                            address: "0x2",
                            module: "bls12381",
                            name: "G2",
                            typeArguments: [],
                          },
                        },
                      ],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
      share: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Vector: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            Vector: {
              Vector: "U8",
            },
          },
          "U64",
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      threshold: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
      verify_and_create_proof: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsMultisigCounter",
                typeArguments: [],
              },
            },
          },
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "bls_multisig_counter",
                name: "BlsAggregatedPk",
                typeArguments: [],
              },
            },
          },
          {
            Vector: "U8",
          },
          {
            Vector: "U8",
          },
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
              module: "bls_multisig_counter",
              name: "BlsMultisigProof",
              typeArguments: [],
            },
          },
        ],
      },
    },
  },
  owned_counter: {
    fileFormatVersion: 6,
    address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
    name: "owned_counter",
    friends: [],
    structs: {
      OwnedCounter: {
        abilities: {
          abilities: ["Store", "Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
        ],
      },
    },
    exposedFunctions: {
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      new: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
              module: "owned_counter",
              name: "OwnedCounter",
              typeArguments: [],
            },
          },
        ],
      },
      set_value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
          "U64",
        ],
        return: [],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "owned_counter",
                name: "OwnedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
    },
  },
  shared_counter: {
    fileFormatVersion: 6,
    address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
    name: "shared_counter",
    friends: [],
    structs: {
      SharedCounter: {
        abilities: {
          abilities: ["Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "value",
            type: "U64",
          },
        ],
      },
    },
    exposedFunctions: {
      increment: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      set_value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
          "U64",
        ],
        return: [],
      },
      share: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      value: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x9bd24ba5fd617512a16ae57fbd84dedbe54d3389e3a227311d16c3159ebcc036",
                module: "shared_counter",
                name: "SharedCounter",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U64"],
      },
    },
  },
} as const;

export type CounterModules = typeof counterAbi;

// Generated TypeScript interfaces
export interface Bls_multisig_counterBlsAggregatedPkType {
  id: { id: string };
  public_key_g2: unknown;
  public_key_bytes: Uint8Array;
  counter_id: unknown;
  seal_shard_count: string;
  included_seal_shard_ids: unknown[];
}

export interface Bls_multisig_counterBlsMultisigConfigType {
  seal_shard_table: { id: string };
  threshold: string;
}

export interface Bls_multisig_counterBlsMultisigCounterType {
  id: { id: string };
  value: string;
  config: unknown;
}

export interface Bls_multisig_counterBlsMultisigProofType {
  id: { id: string };
  counter_id: unknown;
  verified_signer_count: string;
}

export interface Bls_multisig_counterPackageMarkerType {
  dummy_field: boolean;
}

export interface Owned_counterOwnedCounterType {
  id: { id: string };
  value: string;
}

export interface Shared_counterSharedCounterType {
  id: { id: string };
  value: string;
}

// Generated type guards
export function isBls_multisig_counterBlsAggregatedPkType(
  data: unknown,
): data is Bls_multisig_counterBlsAggregatedPkType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = [
    "id",
    "public_key_g2",
    "public_key_bytes",
    "counter_id",
    "seal_shard_count",
    "included_seal_shard_ids",
  ];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["seal_shard_count"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBls_multisig_counterBlsMultisigConfigType(
  data: unknown,
): data is Bls_multisig_counterBlsMultisigConfigType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["seal_shard_table", "threshold"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["threshold"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBls_multisig_counterBlsMultisigCounterType(
  data: unknown,
): data is Bls_multisig_counterBlsMultisigCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value", "config"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBls_multisig_counterBlsMultisigProofType(
  data: unknown,
): data is Bls_multisig_counterBlsMultisigProofType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "counter_id", "verified_signer_count"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["verified_signer_count"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBls_multisig_counterPackageMarkerType(
  data: unknown,
): data is Bls_multisig_counterPackageMarkerType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["dummy_field"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = [];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isOwned_counterOwnedCounterType(
  data: unknown,
): data is Owned_counterOwnedCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isShared_counterSharedCounterType(
  data: unknown,
): data is Shared_counterSharedCounterType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "value"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["value"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

// Generated parse functions
export function parseBls_multisig_counterBlsAggregatedPk(
  json: unknown,
): Bls_multisig_counterBlsAggregatedPkType | null {
  return isBls_multisig_counterBlsAggregatedPkType(json) ? json : null;
}

export function parseBls_multisig_counterBlsMultisigConfig(
  json: unknown,
): Bls_multisig_counterBlsMultisigConfigType | null {
  return isBls_multisig_counterBlsMultisigConfigType(json) ? json : null;
}

export function parseBls_multisig_counterBlsMultisigCounter(
  json: unknown,
): Bls_multisig_counterBlsMultisigCounterType | null {
  return isBls_multisig_counterBlsMultisigCounterType(json) ? json : null;
}

export function parseBls_multisig_counterBlsMultisigProof(
  json: unknown,
): Bls_multisig_counterBlsMultisigProofType | null {
  return isBls_multisig_counterBlsMultisigProofType(json) ? json : null;
}

export function parseBls_multisig_counterPackageMarker(
  json: unknown,
): Bls_multisig_counterPackageMarkerType | null {
  return isBls_multisig_counterPackageMarkerType(json) ? json : null;
}

export function parseOwned_counterOwnedCounter(
  json: unknown,
): Owned_counterOwnedCounterType | null {
  return isOwned_counterOwnedCounterType(json) ? json : null;
}

export function parseShared_counterSharedCounter(
  json: unknown,
): Shared_counterSharedCounterType | null {
  return isShared_counterSharedCounterType(json) ? json : null;
}

// Table types metadata

/**
 * Table<unknown, unknown> metadata
 *
 * Base type: { id: string }
 * Resolved type: Record<unknown, unknown>
 *
 * Usage:
 * 1. Get table ID from base type
 * 2. Fetch table contents using your preferred method (GraphQL, gRPC, etc.)
 * 3. Parse contents into resolved type
 *
 * Example:
 *   const tableId = data.fieldName.id;
 *   const contents = await fetchTableContents(tableId);
 *   const resolvedData: ResolvedType = { ...data, fieldName: contents };
 */

// Extract packageId once at module level for better performance
const packageId = Object.values(counterAbi)[0]?.address;
if (!packageId) {
  throw new Error("Package ID not found in counter ABI");
}

// Type-safe method-chaining API
export const counterPackage = {
  abi: counterAbi,
  packageId,
  bls_multisig_counter: {
    aggregate_seal_shard_pubkey(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::aggregate_seal_shard_pubkey`,
        arguments: [...options.arguments],
      });
    },
    aggregated_key_counter_id(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::aggregated_key_counter_id`,
        arguments: [...options.arguments],
      });
    },
    destroy_bls_aggregated_pk(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::destroy_bls_aggregated_pk`,
        arguments: [...options.arguments],
      });
    },
    get_package_id_bytes(tx: Transaction): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::get_package_id_bytes`,
        arguments: [],
      });
    },
    included_seal_shard_count(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::included_seal_shard_count`,
        arguments: [...options.arguments],
      });
    },
    included_seal_shard_ids(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::included_seal_shard_ids`,
        arguments: [...options.arguments],
      });
    },
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    new_bls_aggregated_pk(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::new_bls_aggregated_pk`,
        arguments: [...options.arguments],
      });
    },
    public_key_g2(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::public_key_g2`,
        arguments: [...options.arguments],
      });
    },
    seal_approve(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::seal_approve`,
        arguments: [...options.arguments],
      });
    },
    seal_shard_count(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::seal_shard_count`,
        arguments: [...options.arguments],
      });
    },
    seal_shard_table(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::seal_shard_table`,
        arguments: [...options.arguments],
      });
    },
    share(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::share`,
        arguments: [...options.arguments],
      });
    },
    threshold(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::threshold`,
        arguments: [...options.arguments],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::value`,
        arguments: [...options.arguments],
      });
    },
    verify_and_create_proof(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bls_multisig_counter::verify_and_create_proof`,
        arguments: [...options.arguments],
      });
    },
  },
  owned_counter: {
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    new(tx: Transaction): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::new`,
        arguments: [],
      });
    },
    set_value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::set_value`,
        arguments: [...options.arguments],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::owned_counter::value`,
        arguments: [...options.arguments],
      });
    },
  },
  shared_counter: {
    increment(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::increment`,
        arguments: [...options.arguments],
      });
    },
    set_value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::set_value`,
        arguments: [...options.arguments],
      });
    },
    share(tx: Transaction): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::share`,
        arguments: [],
      });
    },
    value(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::shared_counter::value`,
        arguments: [...options.arguments],
      });
    },
  },
} as const;
