/**
 * seal package ABI definition with TypeScript interfaces
 * 自動生成されたファイル - 手動で編集しないでください
 *
 * Generated by: scripts/suigenv0.ts
 * Generated at: 2025-09-26T02:40:53.149Z
 */

import {
  type Transaction,
  type TransactionArgument,
  type TransactionResult,
} from "@mysten/sui/transactions";

export const sealAbi = {
  bf_hmac_encryption: {
    fileFormatVersion: 7,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "bf_hmac_encryption",
    friends: [],
    structs: {
      EncryptedObject: {
        abilities: {
          abilities: ["Copy", "Drop", "Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "package_id",
            type: "Address",
          },
          {
            name: "id",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "indices",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "services",
            type: {
              Vector: "Address",
            },
          },
          {
            name: "threshold",
            type: "U8",
          },
          {
            name: "nonce",
            type: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            name: "encrypted_shares",
            type: {
              Vector: {
                Vector: "U8",
              },
            },
          },
          {
            name: "encrypted_randomness",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "blob",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "aad",
            type: {
              Struct: {
                address: "0x1",
                module: "option",
                name: "Option",
                typeArguments: [
                  {
                    Vector: "U8",
                  },
                ],
              },
            },
          },
          {
            name: "mac",
            type: {
              Vector: "U8",
            },
          },
        ],
      },
      PublicKey: {
        abilities: {
          abilities: ["Drop"],
        },
        typeParameters: [],
        fields: [
          {
            name: "key_server",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
          {
            name: "pk",
            type: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
      VerifiedDerivedKey: {
        abilities: {
          abilities: ["Drop", "Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "derived_key",
            type: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G1",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            name: "package_id",
            type: "Address",
          },
          {
            name: "id",
            type: {
              Vector: "U8",
            },
          },
          {
            name: "key_server",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "ID",
                typeArguments: [],
              },
            },
          },
        ],
      },
    },
    enums: {
      KeyPurpose: {
        abilities: {
          abilities: [],
        },
        typeParameters: [],
        variants: {
          DEM: [],
          EncryptedRandomness: [],
        },
        variantDeclarationOrder: ["EncryptedRandomness", "DEM"],
      },
    },
    exposedFunctions: {
      aad: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x1",
                module: "option",
                name: "Option",
                typeArguments: [
                  {
                    Vector: "U8",
                  },
                ],
              },
            },
          },
        ],
      },
      blob: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      decrypt: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                  module: "bf_hmac_encryption",
                  name: "VerifiedDerivedKey",
                  typeArguments: [],
                },
              },
            },
          },
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                  module: "bf_hmac_encryption",
                  name: "PublicKey",
                  typeArguments: [],
                },
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x1",
              module: "option",
              name: "Option",
              typeArguments: [
                {
                  Vector: "U8",
                },
              ],
            },
          },
        ],
      },
      encrypted_randomness: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      encrypted_shares: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: {
                Vector: "U8",
              },
            },
          },
        ],
      },
      id: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      indices: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      mac: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      new_public_key: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Struct: {
              address: "0x2",
              module: "object",
              name: "ID",
              typeArguments: [],
            },
          },
          {
            Vector: "U8",
          },
        ],
        return: [
          {
            Struct: {
              address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
              module: "bf_hmac_encryption",
              name: "PublicKey",
              typeArguments: [],
            },
          },
        ],
      },
      nonce: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
        ],
      },
      package_id: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: "Address",
          },
        ],
      },
      parse_encrypted_object: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Vector: "U8",
          },
        ],
        return: [
          {
            Struct: {
              address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
              module: "bf_hmac_encryption",
              name: "EncryptedObject",
              typeArguments: [],
            },
          },
        ],
      },
      services: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "Address",
            },
          },
        ],
      },
      threshold: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "EncryptedObject",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U8"],
      },
      verify_derived_keys: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x2",
                  module: "group_ops",
                  name: "Element",
                  typeArguments: [
                    {
                      Struct: {
                        address: "0x2",
                        module: "bls12381",
                        name: "G1",
                        typeArguments: [],
                      },
                    },
                  ],
                },
              },
            },
          },
          "Address",
          {
            Vector: "U8",
          },
          {
            Reference: {
              Vector: {
                Struct: {
                  address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                  module: "bf_hmac_encryption",
                  name: "PublicKey",
                  typeArguments: [],
                },
              },
            },
          },
        ],
        return: [
          {
            Vector: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "bf_hmac_encryption",
                name: "VerifiedDerivedKey",
                typeArguments: [],
              },
            },
          },
        ],
      },
    },
  },
  gf256: {
    fileFormatVersion: 6,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "gf256",
    friends: [
      {
        address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
        name: "polynomial",
      },
    ],
    structs: {},
    exposedFunctions: {
      add: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: ["U8", "U8"],
        return: ["U8"],
      },
      div: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: ["U8", "U8"],
        return: ["U8"],
      },
      mul: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: ["U8", "U8"],
        return: ["U8"],
      },
      sub: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: ["U8", "U8"],
        return: ["U8"],
      },
    },
  },
  hmac256ctr: {
    fileFormatVersion: 6,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "hmac256ctr",
    friends: [
      {
        address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
        name: "bf_hmac_encryption",
      },
    ],
    structs: {},
    exposedFunctions: {
      decrypt: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Vector: "U8",
            },
          },
          {
            Reference: {
              Vector: "U8",
            },
          },
          {
            Reference: {
              Vector: "U8",
            },
          },
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x1",
              module: "option",
              name: "Option",
              typeArguments: [
                {
                  Vector: "U8",
                },
              ],
            },
          },
        ],
      },
    },
  },
  kdf: {
    fileFormatVersion: 6,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "kdf",
    friends: [
      {
        address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
        name: "bf_hmac_encryption",
      },
    ],
    structs: {},
    exposedFunctions: {
      hash_to_g1_with_dst: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x2",
              module: "group_ops",
              name: "Element",
              typeArguments: [
                {
                  Struct: {
                    address: "0x2",
                    module: "bls12381",
                    name: "G1",
                    typeArguments: [],
                  },
                },
              ],
            },
          },
        ],
      },
      kdf: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "GT",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G2",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          {
            Reference: {
              Struct: {
                address: "0x2",
                module: "group_ops",
                name: "Element",
                typeArguments: [
                  {
                    Struct: {
                      address: "0x2",
                      module: "bls12381",
                      name: "G1",
                      typeArguments: [],
                    },
                  },
                ],
              },
            },
          },
          "Address",
          "U8",
        ],
        return: [
          {
            Vector: "U8",
          },
        ],
      },
    },
  },
  key_server: {
    fileFormatVersion: 6,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "key_server",
    friends: [],
    structs: {
      KeyServer: {
        abilities: {
          abilities: ["Store", "Key"],
        },
        typeParameters: [],
        fields: [
          {
            name: "id",
            type: {
              Struct: {
                address: "0x2",
                module: "object",
                name: "UID",
                typeArguments: [],
              },
            },
          },
          {
            name: "first_version",
            type: "U64",
          },
          {
            name: "last_version",
            type: "U64",
          },
        ],
      },
      KeyServerV1: {
        abilities: {
          abilities: ["Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "name",
            type: {
              Struct: {
                address: "0x1",
                module: "string",
                name: "String",
                typeArguments: [],
              },
            },
          },
          {
            name: "url",
            type: {
              Struct: {
                address: "0x1",
                module: "string",
                name: "String",
                typeArguments: [],
              },
            },
          },
          {
            name: "key_type",
            type: "U8",
          },
          {
            name: "pk",
            type: {
              Vector: "U8",
            },
          },
        ],
      },
    },
    exposedFunctions: {
      create_and_transfer_v1: {
        visibility: "Private",
        isEntry: true,
        typeParameters: [],
        parameters: [
          {
            Struct: {
              address: "0x1",
              module: "string",
              name: "String",
              typeArguments: [],
            },
          },
          {
            Struct: {
              address: "0x1",
              module: "string",
              name: "String",
              typeArguments: [],
            },
          },
          "U8",
          {
            Vector: "U8",
          },
          {
            MutableReference: {
              Struct: {
                address: "0x2",
                module: "tx_context",
                name: "TxContext",
                typeArguments: [],
              },
            },
          },
        ],
        return: [],
      },
      id: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["Address"],
      },
      key_type: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U8"],
      },
      name: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x1",
              module: "string",
              name: "String",
              typeArguments: [],
            },
          },
        ],
      },
      pk: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
      },
      pk_as_bf_bls12381: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x2",
              module: "group_ops",
              name: "Element",
              typeArguments: [
                {
                  Struct: {
                    address: "0x2",
                    module: "bls12381",
                    name: "G2",
                    typeArguments: [],
                  },
                },
              ],
            },
          },
        ],
      },
      update: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            MutableReference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
          {
            Struct: {
              address: "0x1",
              module: "string",
              name: "String",
              typeArguments: [],
            },
          },
        ],
        return: [],
      },
      url: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x1",
              module: "string",
              name: "String",
              typeArguments: [],
            },
          },
        ],
      },
      v1: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServer",
                typeArguments: [],
              },
            },
          },
        ],
        return: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "key_server",
                name: "KeyServerV1",
                typeArguments: [],
              },
            },
          },
        ],
      },
    },
  },
  polynomial: {
    fileFormatVersion: 6,
    address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
    name: "polynomial",
    friends: [
      {
        address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
        name: "bf_hmac_encryption",
      },
    ],
    structs: {
      Polynomial: {
        abilities: {
          abilities: ["Copy", "Drop", "Store"],
        },
        typeParameters: [],
        fields: [
          {
            name: "coefficients",
            type: {
              Vector: "U8",
            },
          },
        ],
      },
    },
    exposedFunctions: {
      evaluate: {
        visibility: "Public",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "polynomial",
                name: "Polynomial",
                typeArguments: [],
              },
            },
          },
          "U8",
        ],
        return: ["U8"],
      },
      get_constant_term: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Struct: {
                address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
                module: "polynomial",
                name: "Polynomial",
                typeArguments: [],
              },
            },
          },
        ],
        return: ["U8"],
      },
      interpolate: {
        visibility: "Friend",
        isEntry: false,
        typeParameters: [],
        parameters: [
          {
            Reference: {
              Vector: "U8",
            },
          },
          {
            Reference: {
              Vector: "U8",
            },
          },
        ],
        return: [
          {
            Struct: {
              address: "0x73bba649fe918ef501e2fb6ab82e83450a4c286f52cf3399e678e6da257f0c50",
              module: "polynomial",
              name: "Polynomial",
              typeArguments: [],
            },
          },
        ],
      },
    },
  },
} as const;

export type SealModules = typeof sealAbi;

// Generated TypeScript interfaces
export interface Bf_hmac_encryptionEncryptedObjectType {
  package_id: string;
  id: Uint8Array;
  indices: Uint8Array;
  services: string[];
  threshold: number;
  nonce: unknown;
  encrypted_shares: Uint8Array[];
  encrypted_randomness: Uint8Array;
  blob: Uint8Array;
  aad: unknown;
  mac: Uint8Array;
}

export interface Bf_hmac_encryptionPublicKeyType {
  key_server: unknown;
  pk: unknown;
}

export interface Bf_hmac_encryptionVerifiedDerivedKeyType {
  derived_key: unknown;
  package_id: string;
  id: Uint8Array;
  key_server: unknown;
}

export interface Key_serverKeyServerType {
  id: { id: string };
  first_version: string;
  last_version: string;
}

export interface Key_serverKeyServerV1Type {
  name: string;
  url: string;
  key_type: number;
  pk: Uint8Array;
}

export interface PolynomialPolynomialType {
  coefficients: Uint8Array;
}

// Generated type guards
export function isBf_hmac_encryptionEncryptedObjectType(
  data: unknown,
): data is Bf_hmac_encryptionEncryptedObjectType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = [
    "package_id",
    "id",
    "indices",
    "services",
    "threshold",
    "nonce",
    "encrypted_shares",
    "encrypted_randomness",
    "blob",
    "aad",
    "mac",
  ];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["package_id"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBf_hmac_encryptionPublicKeyType(
  data: unknown,
): data is Bf_hmac_encryptionPublicKeyType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["key_server", "pk"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = [];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isBf_hmac_encryptionVerifiedDerivedKeyType(
  data: unknown,
): data is Bf_hmac_encryptionVerifiedDerivedKeyType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["derived_key", "package_id", "id", "key_server"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["package_id"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isKey_serverKeyServerType(data: unknown): data is Key_serverKeyServerType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["id", "first_version", "last_version"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["first_version", "last_version"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isKey_serverKeyServerV1Type(data: unknown): data is Key_serverKeyServerV1Type {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["name", "url", "key_type", "pk"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = ["name", "url"];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

export function isPolynomialPolynomialType(data: unknown): data is PolynomialPolynomialType {
  if (!data || typeof data !== "object") return false;
  const obj = data as Record<string, unknown>;

  // 必須フィールドの存在確認
  const requiredFields = ["coefficients"];
  for (const field of requiredFields) {
    if (!(field in obj)) return false;
  }

  // string型フィールドの型確認
  const stringFields: string[] = [];
  for (const field of stringFields) {
    if (typeof obj[field] !== "string") return false;
  }

  return true;
}

// Generated parse functions
export function parseBf_hmac_encryptionEncryptedObject(
  json: unknown,
): Bf_hmac_encryptionEncryptedObjectType | null {
  return isBf_hmac_encryptionEncryptedObjectType(json) ? json : null;
}

export function parseBf_hmac_encryptionPublicKey(
  json: unknown,
): Bf_hmac_encryptionPublicKeyType | null {
  return isBf_hmac_encryptionPublicKeyType(json) ? json : null;
}

export function parseBf_hmac_encryptionVerifiedDerivedKey(
  json: unknown,
): Bf_hmac_encryptionVerifiedDerivedKeyType | null {
  return isBf_hmac_encryptionVerifiedDerivedKeyType(json) ? json : null;
}

export function parseKey_serverKeyServer(json: unknown): Key_serverKeyServerType | null {
  return isKey_serverKeyServerType(json) ? json : null;
}

export function parseKey_serverKeyServerV1(json: unknown): Key_serverKeyServerV1Type | null {
  return isKey_serverKeyServerV1Type(json) ? json : null;
}

export function parsePolynomialPolynomial(json: unknown): PolynomialPolynomialType | null {
  return isPolynomialPolynomialType(json) ? json : null;
}

// Extract packageId once at module level for better performance
const packageId = Object.values(sealAbi)[0]?.address;
if (!packageId) {
  throw new Error("Package ID not found in seal ABI");
}

// Type-safe method-chaining API
export const sealPackage = {
  abi: sealAbi,
  packageId,
  bf_hmac_encryption: {
    aad(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::aad`,
        arguments: [...options.arguments],
      });
    },
    blob(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::blob`,
        arguments: [...options.arguments],
      });
    },
    decrypt(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::decrypt`,
        arguments: [...options.arguments],
      });
    },
    encrypted_randomness(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::encrypted_randomness`,
        arguments: [...options.arguments],
      });
    },
    encrypted_shares(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::encrypted_shares`,
        arguments: [...options.arguments],
      });
    },
    id(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::id`,
        arguments: [...options.arguments],
      });
    },
    indices(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::indices`,
        arguments: [...options.arguments],
      });
    },
    mac(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::mac`,
        arguments: [...options.arguments],
      });
    },
    new_public_key(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::new_public_key`,
        arguments: [...options.arguments],
      });
    },
    nonce(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::nonce`,
        arguments: [...options.arguments],
      });
    },
    package_id(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::package_id`,
        arguments: [...options.arguments],
      });
    },
    parse_encrypted_object(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::parse_encrypted_object`,
        arguments: [...options.arguments],
      });
    },
    services(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::services`,
        arguments: [...options.arguments],
      });
    },
    threshold(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::threshold`,
        arguments: [...options.arguments],
      });
    },
    verify_derived_keys(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::bf_hmac_encryption::verify_derived_keys`,
        arguments: [...options.arguments],
      });
    },
  },
  gf256: {
    add(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::gf256::add`,
        arguments: [...options.arguments],
      });
    },
    div(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::gf256::div`,
        arguments: [...options.arguments],
      });
    },
    mul(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::gf256::mul`,
        arguments: [...options.arguments],
      });
    },
    sub(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::gf256::sub`,
        arguments: [...options.arguments],
      });
    },
  },
  hmac256ctr: {
    decrypt(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::hmac256ctr::decrypt`,
        arguments: [...options.arguments],
      });
    },
  },
  kdf: {
    hash_to_g1_with_dst(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::kdf::hash_to_g1_with_dst`,
        arguments: [...options.arguments],
      });
    },
    kdf(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::kdf::kdf`,
        arguments: [...options.arguments],
      });
    },
  },
  key_server: {
    create_and_transfer_v1(
      tx: Transaction,
      options: {
        arguments: readonly [
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
          TransactionArgument,
        ];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::create_and_transfer_v1`,
        arguments: [...options.arguments],
      });
    },
    id(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::id`,
        arguments: [...options.arguments],
      });
    },
    key_type(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::key_type`,
        arguments: [...options.arguments],
      });
    },
    name(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::name`,
        arguments: [...options.arguments],
      });
    },
    pk(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::pk`,
        arguments: [...options.arguments],
      });
    },
    pk_as_bf_bls12381(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::pk_as_bf_bls12381`,
        arguments: [...options.arguments],
      });
    },
    update(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::update`,
        arguments: [...options.arguments],
      });
    },
    url(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::url`,
        arguments: [...options.arguments],
      });
    },
    v1(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::key_server::v1`,
        arguments: [...options.arguments],
      });
    },
  },
  polynomial: {
    evaluate(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::polynomial::evaluate`,
        arguments: [...options.arguments],
      });
    },
    get_constant_term(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::polynomial::get_constant_term`,
        arguments: [...options.arguments],
      });
    },
    interpolate(
      tx: Transaction,
      options: {
        arguments: readonly [TransactionArgument, TransactionArgument];
      },
    ): TransactionResult {
      return tx.moveCall({
        target: `${packageId}::polynomial::interpolate`,
        arguments: [...options.arguments],
      });
    },
  },
} as const;
