/**
 * Multi-IBS Seal Aggregator Library
 *
 * This module provides the SealMultiIBSAggregator class for integrating
 * Seal Key Servers with Multi-IBS signature aggregation.
 */

import { type KeyServerConfig, SealClient, SessionKey } from "@mysten/seal";
import { getFullnodeUrl, SuiClient } from "@mysten/sui/client";
import { type Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { Transaction } from "@mysten/sui/transactions";
import { bls12_381 } from "@noble/curves/bls12-381.js";

const NETWORK = "testnet" as const;
const THRESHOLD = 2; // 2-of-3 threshold
const COUNTER_PACKAGE_ID = "0x6ce277618bf01afd77ef1de3ff19dda6df713387aaf91d53f6a58c5904b5ec21";

export interface KeyShare {
  serverIndex: number;
  serverId: string;
  /**
   * sk_ID_i as G1Element bytes (typically 48 bytes compressed)
   *
   * This is the IBE secret key from Key Server i for identity ID:
   * - Generated by: sk_ID_i = H₁(ID) × msk_i
   * - H₁: hash-to-G1 function (deterministic)
   * - msk_i: master secret key of Key Server i (kept secret)
   * - Result: G1 curve point that can be used for BLS signatures
   *
   * Security properties:
   * - Each server can independently compute this
   * - Servers never need to communicate with each other
   * - Aggregation happens client-side: sk_ID = Σ sk_ID_i
   */
  secretKey: Uint8Array; // sk_ID_i as G1Element bytes
}

export interface MultiIBSSignature {
  signature: Uint8Array; // G1 signature (48 bytes)
  message: Uint8Array;
  identity: string;
}

export class SealMultiIBSAggregator {
  private suiClient: SuiClient;
  private sealClient: SealClient;

  constructor(network: "testnet" | "mainnet" = NETWORK) {
    this.suiClient = new SuiClient({ url: getFullnodeUrl(network) });

    // Initialize SealClient for real Key Server operations
    const serverConfigs: KeyServerConfig[] = [
      {
        objectId: "0x164ac3d2b3b8694b8181c13f671950004765c23f270321a45fdd04d40cccf0f2",
        weight: 1,
      },
      {
        objectId: "0x6068c0acb197dddbacd4746a9de7f025b2ed5a5b6c1b1ab44dade4426d141da2",
        weight: 1,
      },
      {
        objectId: "0x5466b7df5c15b508678d51496ada8afab0d6f70a01c10613123382b1b8131007",
        weight: 1,
      },
    ];

    this.sealClient = new SealClient({
      suiClient: this.suiClient,
      serverConfigs,
      verifyKeyServers: false,
    });
  }

  /**
   * Retrieve sk_ID_i from Seal Key Servers for a specific message
   * @param counterId Multi-IBS counter object ID
   * @param signerKeypair Ed25519 keypair for signing
   * @param message The message to sign
   * @param requiredCount Number of key shares needed
   */
  async fetchSecretKeyShares(
    counterId: string,
    signerKeypair: Ed25519Keypair,
    message: string,
    requiredCount: number = THRESHOLD,
  ): Promise<KeyShare[]> {
    try {
      // Step 1: Construct IBE Identity = counter_id || signer_address || message
      const signerAddress = signerKeypair.getPublicKey().toSuiAddress();
      const messageBytes = new TextEncoder().encode(message);

      // Prepare message with domain separation matching Move contract
      const messageWithDomain = new Uint8Array([
        ...new TextEncoder().encode("SUI-MULTI-IBS-V1"),
        ...messageBytes,
      ]);

      // Convert counter ID to bytes (same as Move object::id().to_bytes())
      const counterIdBytes = Array.from(Buffer.from(counterId.replace("0x", ""), "hex"));

      // Convert signer address to bytes (same as Move bcs::to_bytes(&address))
      const signerBytes = Array.from(Buffer.from(signerAddress.replace("0x", ""), "hex"));

      // Concatenate: counter_id || signer_address || message_with_domain
      const ibeIdBytes = [...counterIdBytes, ...signerBytes, ...Array.from(messageWithDomain)];

      // Convert to hex string for Seal SDK
      const ibeIdHex = `0x${Buffer.from(ibeIdBytes).toString("hex")}`;

      const sessionKey = await SessionKey.create({
        address: signerAddress,
        packageId: COUNTER_PACKAGE_ID,
        ttlMin: 10,
        signer: signerKeypair,
        suiClient: this.suiClient,
      });

      // Step 3: Build seal_approve transaction for txBytes (DO NOT EXECUTE)
      const approveTx = new Transaction();
      approveTx.moveCall({
        target: `${COUNTER_PACKAGE_ID}::multi_ibs_counter::seal_approve`,
        arguments: [
          approveTx.pure.vector("u8", ibeIdBytes),
          approveTx.object(counterId),
          approveTx.pure.vector("u8", Array.from(messageBytes)),
        ],
      });

      // Generate txBytes without executing the transaction
      const txBytes = await approveTx.build({
        client: this.suiClient,
        onlyTransactionKind: true,
      });

      // Step 4: Get IBE derived keys from Key Servers
      const derivedKeys = await this.sealClient.getDerivedKeys({
        id: ibeIdHex,
        sessionKey,
        txBytes,
        threshold: requiredCount,
      });

      // Check if derivedKeys is a Map
      if (!derivedKeys || typeof derivedKeys.size !== "number") {
        throw new Error(`getDerivedKeys returned unexpected result: ${derivedKeys}`);
      }

      // Step 5: Convert Map to KeyShare format
      const keyShares: KeyShare[] = [];
      let serverIndex = 0;

      for (const [serverId, derivedKey] of derivedKeys) {
        // Derived key has a key property with toBytes method
        const keyBytes = (derivedKey as { key: { toBytes(): Uint8Array } }).key.toBytes();

        keyShares.push({
          serverIndex,
          serverId,
          secretKey: keyBytes,
        });
        serverIndex++;
      }

      return keyShares;
    } catch (error) {
      const errorMessage = (error as Error)?.message || String(error) || "Unknown error";
      throw new Error(
        `Real Key Server integration failed: ${errorMessage}. Mock fallback is forbidden.`,
      );
    }
  }

  /**
   * Aggregate IBE secret keys (G1 elements) directly as signature
   */
  aggregateIBESignature(keyShares: KeyShare[]): Uint8Array {
    if (keyShares.length === 0) {
      throw new Error("No key shares to aggregate");
    }

    const firstKey = keyShares[0]?.secretKey;
    if (!firstKey) throw new Error("No key shares available");

    let aggregatedSignature = bls12_381.G1.Point.fromBytes(firstKey);

    for (let i = 1; i < keyShares.length; i++) {
      const keyShare = keyShares[i]?.secretKey;
      if (!keyShare) continue;
      const ibeKey = bls12_381.G1.Point.fromBytes(keyShare);
      aggregatedSignature = aggregatedSignature.add(ibeKey);
    }

    const result = aggregatedSignature.toBytes(true); // 48 bytes compressed G1 point
    return result;
  }

  /**
   * Legacy method for compatibility - now delegates to IBE signature aggregation
   */
  aggregateSecretKeys(keyShares: KeyShare[]): Uint8Array {
    return this.aggregateIBESignature(keyShares);
  }

  /**
   * Create Multi-IBS signature using aggregated IBE signature
   */
  createMultiIBSSignature(
    aggregatedIBESignature: Uint8Array,
    message: string,
    identity: string,
  ): MultiIBSSignature {
    const messageBytes = new TextEncoder().encode(message);

    return {
      signature: aggregatedIBESignature,
      message: messageBytes,
      identity,
    };
  }

  /**
   * Get public key for a specific Key Server
   */
  async getKeyServerPublicKey(keyServerId: string): Promise<Uint8Array> {
    try {
      const publicKeys = await this.sealClient.getPublicKeys([keyServerId]);

      if (!publicKeys || publicKeys.length === 0) {
        throw new Error(`No public key found for Key Server: ${keyServerId}`);
      }

      // Public key should have a toBytes method based on Seal SDK implementation
      return (
        (publicKeys[0] as { toBytes(): Uint8Array } | undefined)?.toBytes() ?? new Uint8Array()
      );
    } catch (error) {
      throw new Error(`Failed to get public key for ${keyServerId}: ${error}`);
    }
  }
}

/**
 * Fetch real public keys from Seal Key Servers for counter creation
 * This is used during counter initialization to set up the Key Server configuration
 */
export async function createSealShardCounterConfig(
  keyServerIds: string[],
  threshold: number,
  network: "testnet" | "mainnet" = "testnet",
): Promise<{ keyServerIds: string[]; publicKeys: number[][]; threshold: number }> {
  const aggregator = new SealMultiIBSAggregator(network);
  const publicKeys: number[][] = [];

  for (const keyServerId of keyServerIds) {
    try {
      const publicKey = await aggregator.getKeyServerPublicKey(keyServerId);
      publicKeys.push(Array.from(publicKey));
    } catch (_error) {
      // Generate deterministic but valid G2 element as fallback
      const { bls12_381 } = await import("@noble/curves/bls12-381.js");
      const keyBytes = new TextEncoder().encode(keyServerId);
      const hash = await crypto.subtle.digest("SHA-256", keyBytes);
      const hashArray = new Uint8Array(hash);
      const scalar = hashArray.slice(0, 32);

      const g2Generator = bls12_381.G2.Point.BASE;
      const scalarBigInt = BigInt(
        `0x${Array.from(scalar)
          .map((b) => b.toString(16).padStart(2, "0"))
          .join("")}`,
      );
      const reducedScalar = scalarBigInt % bls12_381.fields.Fr.ORDER;
      const scalaredPoint = g2Generator.multiply(reducedScalar);
      const publicKey = scalaredPoint.toBytes(true);
      publicKeys.push(Array.from(publicKey));
    }
  }

  return {
    keyServerIds,
    publicKeys,
    threshold,
  };
}
