#!/usr/bin/env tsx

/**
 * Multi-IBS with Seal SDK Integration
 *
 * This script demonstrates how to integrate actual Seal Key Servers
 * with Multi-IBS signature aggregation using:
 * 1. Seal SDK for sk_ID_i retrieval from Key Servers
 * 2. @noble/curves for BLS signature operations
 * 3. G1Element aggregation from multiple Key Servers
 * 4. Real cryptographic Multi-IBS implementation
 *
 * ===== KEY CONCEPT: sk_ID_i as G1Element =====
 *
 * What is sk_ID_i?
 * - Identity-Based Encryption (IBE) secret key for identity ID
 * - Generated by Seal Key Server i: sk_ID_i = H₁(ID) × msk_i
 * - H₁ is hash-to-G1, msk_i is master secret key of server i
 * - sk_ID_i is a G1Element (48 bytes compressed)
 *
 * Why can we use IBE keys for signatures?
 * - IBE secret keys are mathematically compatible with BLS signatures
 * - sk_ID = Σ sk_ID_i enables threshold signature capability
 * - Each sk_ID_i can independently create valid signatures
 * - Aggregation maintains security properties
 *
 * Mock vs Real implementation:
 * - This script includes both mock (for demo) and real Seal integration
 * - Real usage would uncomment the Seal SDK calls
 * - Mock keys are deterministic for testing consistency
 */

import { SealClient, SessionKey } from "@mysten/seal";
import { bcs } from "@mysten/sui/bcs";
import { getFullnodeUrl, SuiClient } from "@mysten/sui/client";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { Transaction } from "@mysten/sui/transactions";
import { bls12_381 } from "@noble/curves/bls12-381.js";
import { counterPackage } from "../src/abi/index.js";

/**
 * CRITICAL: Same signature scheme choice as test file
 *
 * We use shortSignatures (G1 signatures, G2 public keys) for:
 * - 48-byte signatures (efficient on-chain storage)
 * - 96-byte public keys (aggregated once, stored off-chain in Key Servers)
 * - Consistency with Move contract expectations
 * - Optimal gas costs for repeated signature verification
 */
const blss = bls12_381.shortSignatures;

// Configuration
const NETWORK = "testnet";
const PACKAGE_ID = counterPackage.$address;
/**
 * THRESHOLD SIGNATURE CONFIGURATION
 *
 * 2-of-3 threshold means:
 * - Any 2 Key Servers can cooperate to create valid signatures
 * - Single Key Server compromise doesn't break security
 * - Provides fault tolerance (1 server can be offline)
 * - Balances security vs availability
 *
 * Higher thresholds (e.g., 3-of-5) would provide more security
 * but reduce availability and increase coordination complexity.
 */
const THRESHOLD = 2; // 2-of-3 threshold

/**
 * Seal Key Server configurations (Testnet servers)
 *
 * These are real Key Server object IDs on Sui testnet:
 * - Each server has its own master secret key (msk_i)
 * - Servers cooperate to provide threshold IBE service
 * - Object IDs are publicly known, but master keys are kept secret
 * - Each server independently computes sk_ID_i for given identity ID
 */
const KEY_SERVERS = [
  {
    name: "Studio Mirai",
    objectId: "0x164ac3d2b3b8694b8181c13f671950004765c23f270321a45fdd04d40cccf0f2",
  },
  {
    name: "Ruby Node",
    objectId: "0x6068c0acb197dddbacd4746a9de7f025b2ed5a5b6c1b1ab44dade4426d141da2",
  },
  {
    name: "NodeInfra",
    objectId: "0x5466b7df5c15b508678d51496ada8afab0d6f70a01c10613123382b1b8131007",
  },
];

interface KeyShare {
  serverIndex: number;
  serverId: string;
  /**
   * sk_ID_i as G1Element bytes (typically 48 bytes compressed)
   *
   * This is the IBE secret key from Key Server i for identity ID:
   * - Generated by: sk_ID_i = H₁(ID) × msk_i
   * - H₁: hash-to-G1 function (deterministic)
   * - msk_i: master secret key of Key Server i (kept secret)
   * - Result: G1 curve point that can be used for BLS signatures
   *
   * Security properties:
   * - Each server can independently compute this
   * - Servers never need to communicate with each other
   * - Aggregation happens client-side: sk_ID = Σ sk_ID_i
   */
  secretKey: Uint8Array; // sk_ID_i as G1Element bytes
}

interface MultiIBSSignature {
  signature: Uint8Array; // G1 signature (48 bytes)
  message: Uint8Array;
  identity: string;
}

class SealMultiIBSAggregator {
  private suiClient: SuiClient;
  private sealClient: SealClient;

  constructor() {
    this.suiClient = new SuiClient({ url: getFullnodeUrl(NETWORK) });

    // Initialize SealClient only if needed for real operations
    // For demo purposes, we'll skip real Seal initialization
    this.sealClient = null as any; // Will use mock keys instead
  }

  /**
   * Retrieve sk_ID_i from Seal Key Servers
   */
  async fetchSecretKeyShares(
    identity: string,
    signerKeypair: Ed25519Keypair,
    requiredCount: number = THRESHOLD
  ): Promise<KeyShare[]> {
    /**
     * REAL SEAL SDK INTEGRATION (currently disabled for demo)
     *
     * In production, this function would:
     * 1. Create session key with SessionKey.create()
     *    - Authorizes dApp to request keys for limited time
     *    - User signs once, dApp can make multiple requests
     *    - Prevents need for repeated user wallet confirmations
     *
     * 2. Build approval transaction
     *    - Creates PTB for identity-based key request
     *    - Includes identity bytes and message/context
     *    - Required by Key Servers for authorization
     *
     * 3. Fetch keys from Seal servers with fetchKeys()
     *    - SDK automatically contacts multiple Key Servers
     *    - Each server returns sk_ID_i for the identity
     *    - Threshold requirement ensures enough keys are retrieved
     *
     * 4. Extract G1Element secret keys
     *    - Convert returned data to Uint8Array
     *    - Validate G1 point format (48 bytes compressed)
     *    - Prepare for client-side aggregation
     *
     * Current status: Using mock keys for demo stability
     * To enable real Seal: uncomment the code above and set this.sealClient
     */
    console.warn("⚠️  Using mock keys for demo (Seal SDK integration code is available but disabled)");
    return this.generateMockKeyShares(identity, requiredCount);
  }

  /**
   * Generate mock key shares for development/testing
   *
   * IMPORTANT: Mock keys simulate the same mathematical properties as real keys:
   * - Deterministic generation based on identity + server index
   * - Different keys for different servers (simulates independent msk_i)
   * - Consistent results for same identity (enables reproducible testing)
   * - Valid 32-byte format (compatible with BLS scalar operations)
   *
   * Mock vs Real difference:
   * - Mock: Simple hash-based derivation (fast, reproducible)
   * - Real: Proper IBE key derivation with hash-to-G1 (secure, from Key Servers)
   *
   * Security note: Mock keys are NOT secure for production!
   * They're only for development and testing purposes.
   */
  private generateMockKeyShares(identity: string, count: number): KeyShare[] {
    const shares: KeyShare[] = [];

    for (let i = 0; i < count; i++) {
      // Create deterministic mock key based on identity + server
      const seed = new TextEncoder().encode(`${identity}:${i}:${KEY_SERVERS[i].name}`);
      const secretKey = new Uint8Array(32);

      for (let j = 0; j < 32; j++) {
        secretKey[j] = seed[j % seed.length] ^ (i * 17 + j * 31) & 0xFF;
      }

      shares.push({
        serverIndex: i,
        serverId: KEY_SERVERS[i].objectId,
        secretKey,
      });
    }

    return shares;
  }

  /**
   * Aggregate secret key shares: sk_ID = sk_ID_1 + sk_ID_2 + ... + sk_ID_n
   * Using modular addition over the BLS12-381 scalar field
   */
  aggregateSecretKeys(keyShares: KeyShare[]): Uint8Array {
    if (keyShares.length === 0) {
      throw new Error("No key shares to aggregate");
    }

    // Convert first key to bigint
    let aggregated = this.bytesToBigInt(keyShares[0].secretKey);

    // Add remaining keys modulo curve order
    for (let i = 1; i < keyShares.length; i++) {
      const keyBigInt = this.bytesToBigInt(keyShares[i].secretKey);
      aggregated = (aggregated + keyBigInt) % bls12_381.fields.Fr.ORDER;
    }

    return this.bigIntToBytes(aggregated, 32);
  }

  /**
   * Create Multi-IBS signature using aggregated secret key
   */
  createMultiIBSSignature(
    aggregatedSecretKey: Uint8Array,
    message: string,
    identity: string
  ): MultiIBSSignature {
    const messageBytes = new TextEncoder().encode(message);

    // Hash message to G1 curve point with Move contract domain separation
    // Move uses: DOMAIN_SEPARATOR_BLS = b"SUI-MULTI-IBS-V1"
    const messageWithDomain = new Uint8Array([
      ...new TextEncoder().encode("SUI-MULTI-IBS-V1"),
      ...messageBytes
    ]);
    const DST = 'BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_';
    const hashedMessage = blss.hash(messageWithDomain, DST);

    // Create G1 signature
    const signature = blss.sign(hashedMessage, aggregatedSecretKey);

    return {
      signature: signature.toBytes(),
      message: messageBytes,
      identity,
    };
  }

  /**
   * Verify Multi-IBS signature before submission
   */
  verifyMultiIBSSignature(
    multiSig: MultiIBSSignature,
    aggregatedPublicKey: Uint8Array
  ): boolean {
    // Use same domain separation as Move contract
    const messageWithDomain = new Uint8Array([
      ...new TextEncoder().encode("SUI-MULTI-IBS-V1"),
      ...multiSig.message
    ]);
    const DST = 'BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_';
    const hashedMessage = blss.hash(messageWithDomain, DST);

    // Convert bytes back to Point objects for verification
    const sigPoint = bls12_381.G1.Point.fromBytes(multiSig.signature);
    const pubKeyPoint = bls12_381.G2.Point.fromBytes(aggregatedPublicKey);

    return blss.verify(sigPoint, hashedMessage, pubKeyPoint);
  }

  /**
   * Submit Multi-IBS signature to blockchain for verification
   */
  async submitMultiIBSSignature(
    counterId: string,
    multiSig: MultiIBSSignature,
    signerKeypair: Ed25519Keypair
  ): Promise<string> {
    const tx = new Transaction();

    // Call verify_and_create_proof with aggregated signature
    const proof = tx.moveCall({
      target: `${PACKAGE_ID}::multi_ibs_counter::verify_and_create_proof`,
      arguments: [
        tx.object(counterId),
        tx.pure.vector("u8", Array.from(multiSig.signature)),
        tx.pure.vector("u8", Array.from(multiSig.message)),
      ],
    });

    // Use proof to increment counter
    tx.moveCall({
      target: `${PACKAGE_ID}::multi_ibs_counter::increment`,
      arguments: [tx.object(counterId), proof],
    });

    const result = await this.suiClient.signAndExecuteTransaction({
      signer: signerKeypair,
      transaction: tx,
      options: { showEffects: true, showObjectChanges: true },
    });

    if (result.effects?.status?.status !== "success") {
      throw new Error(`Transaction failed: ${result.effects?.status?.error}`);
    }

    return result.digest;
  }

  /**
   * Get public key from secret key
   */
  getPublicKey(secretKey: Uint8Array): Uint8Array {
    return blss.getPublicKey(secretKey).toBytes();
  }

  // Helper methods
  private bytesToBigInt(bytes: Uint8Array): bigint {
    let result = 0n;
    for (let i = 0; i < bytes.length; i++) {
      result = (result << 8n) + BigInt(bytes[i]);
    }
    return result;
  }

  private bigIntToBytes(value: bigint, length: number): Uint8Array {
    const result = new Uint8Array(length);
    for (let i = length - 1; i >= 0; i--) {
      result[i] = Number(value & 0xFFn);
      value >>= 8n;
    }
    return result;
  }
}

// Demo function
async function demonstrateMultiIBS() {
  const aggregator = new SealMultiIBSAggregator();
  const signerKeypair = Ed25519Keypair.generate();

  console.log("🚀 Multi-IBS with Seal SDK Demo");
  console.log("================================");

  try {
    // Step 1: Fetch secret key shares from Seal servers
    const identity = signerKeypair.getPublicKey().toSuiAddress();
    console.log(`👤 Identity: ${identity}`);

    console.log("📡 Fetching secret key shares from Seal servers...");
    const keyShares = await aggregator.fetchSecretKeyShares(identity, signerKeypair, 2);
    console.log(`✅ Retrieved ${keyShares.length} key shares`);

    // Step 2: Aggregate secret keys
    console.log("🔗 Aggregating secret keys...");
    const aggregatedSK = aggregator.aggregateSecretKeys(keyShares);
    const aggregatedPK = aggregator.getPublicKey(aggregatedSK);
    console.log(`✅ Aggregated secret key (${aggregatedSK.length} bytes)`);

    // Step 3: Create Multi-IBS signature
    const message = `increment-counter-${Date.now()}`;
    console.log(`✍️  Signing message: "${message}"`);

    const multiSig = aggregator.createMultiIBSSignature(aggregatedSK, message, identity);
    console.log(`✅ Created G1 signature (${multiSig.signature.length} bytes)`);

    // Step 4: Verify signature locally
    console.log("🔍 Verifying signature locally...");
    const isValid = aggregator.verifyMultiIBSSignature(multiSig, aggregatedPK);
    console.log(`✅ Signature verification: ${isValid ? "VALID" : "INVALID"}`);

    if (!isValid) {
      throw new Error("Signature verification failed");
    }

    console.log("🎉 Multi-IBS signature creation and verification successful!");

    // Note: Blockchain submission would require deployed contract
    // const txDigest = await aggregator.submitMultiIBSSignature(counterId, multiSig, signerKeypair);
    // console.log(`📝 Transaction submitted: ${txDigest}`);

  } catch (error) {
    console.error("❌ Demo failed:", error);
    process.exit(1);
  }
}

// Execute demo if run directly
if (import.meta.url === `file://${process.argv[1]}`) {
  demonstrateMultiIBS();
}

export { SealMultiIBSAggregator };